version: '3.9'
# despliega api SRIT con un contenedor alojando el api y un contenedor con la db en mongo 
services:
  srit:
    build: .
    ports:
      - "5000:5000"


  mongo-server:
    image: mongo:latest
    container_name: mongo-server
    ports:
      - "27017:27017"

    volumes:
      - mongo_data:/data/db


volumes:
  mongo_data:



